// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface AuthReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.AuthReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   * device id(手机设备id)
   * </pre>
   *
   * <code>optional string deviceId = 2;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * device id(手机设备id)
   * </pre>
   *
   * <code>optional string deviceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>optional string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   *clienttype客户端类型1-pc 2-android 3-ios
   * </pre>
   *
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  int getDeviceTypeValue();
  /**
   * <pre>
   *clienttype客户端类型1-pc 2-android 3-ios
   * </pre>
   *
   * <code>optional .src.main.proto.DeviceType deviceType = 4;</code>
   */
  com.zhongweixian.entity.DeviceType getDeviceType();

  /**
   * <pre>
   *渠道号
   * </pre>
   *
   * <code>optional string cid = 5;</code>
   */
  java.lang.String getCid();
  /**
   * <pre>
   *渠道号
   * </pre>
   *
   * <code>optional string cid = 5;</code>
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <pre>
   *app版本号
   * </pre>
   *
   * <code>optional string appVersion = 6;</code>
   */
  java.lang.String getAppVersion();
  /**
   * <pre>
   *app版本号
   * </pre>
   *
   * <code>optional string appVersion = 6;</code>
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <pre>
   *手机型号信息，譬如华为某型号
   * </pre>
   *
   * <code>optional string deviceInfo = 7;</code>
   */
  java.lang.String getDeviceInfo();
  /**
   * <pre>
   *手机型号信息，譬如华为某型号
   * </pre>
   *
   * <code>optional string deviceInfo = 7;</code>
   */
  com.google.protobuf.ByteString
      getDeviceInfoBytes();

  /**
   * <pre>
   *序列号
   * </pre>
   *
   * <code>optional int64 seq = 8;</code>
   */
  long getSeq();

  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>optional string sign = 9;</code>
   */
  java.lang.String getSign();
  /**
   * <pre>
   *签名
   * </pre>
   *
   * <code>optional string sign = 9;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
