// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_AuthReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_AuthReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_AuthRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_AuthRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_JoinReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_JoinReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_JoinRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_JoinRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_MessagesReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_MessagesReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_MessagesRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_MessagesRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_BeginToLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_BeginToLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_BeginToLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_BeginToLiveRespBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_EndLiveReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_EndLiveReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_src_main_proto_EndLiveRespBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_src_main_proto_EndLiveRespBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\016src.main.proto\"\274\001\n\013AuthReq" +
      "Body\022\014\n\004time\030\001 \001(\003\022\020\n\010deviceId\030\002 \001(\t\022\r\n\005" +
      "token\030\003 \001(\t\022.\n\ndeviceType\030\004 \001(\0162\032.src.ma" +
      "in.proto.DeviceType\022\013\n\003cid\030\005 \001(\t\022\022\n\nappV" +
      "ersion\030\006 \001(\t\022\022\n\ndeviceInfo\030\007 \001(\t\022\013\n\003seq\030" +
      "\010 \001(\003\022\014\n\004sign\030\t \001(\t\"\034\n\014AuthRespBody\022\014\n\004t" +
      "ime\030\001 \001(\003\"*\n\013JoinReqBody\022\014\n\004time\030\001 \001(\003\022\r" +
      "\n\005group\030\002 \001(\t\"\\\n\014JoinRespBody\022\014\n\004time\030\001 " +
      "\001(\003\022/\n\006result\030\002 \001(\0162\037.src.main.proto.Joi" +
      "nGroupResult\022\r\n\005group\030\003 \001(\t\"\272\001\n\017Messages",
      "ReqBody\022\014\n\004time\030\001 \001(\003\022*\n\010chatType\030\002 \001(\0162" +
      "\030.src.main.proto.ChatType\022\014\n\004text\030\003 \001(\t\022" +
      "\r\n\005group\030\004 \001(\t\022\016\n\006fromId\030\005 \001(\005\022\014\n\004toId\030\006" +
      " \001(\005\0222\n\014messagesType\030\007 \001(\0162\034.src.main.pr" +
      "oto.MessagesType\"\267\001\n\020MessagesRespBody\022\014\n" +
      "\004time\030\001 \001(\003\022&\n\004type\030\002 \001(\0162\030.src.main.pro" +
      "to.ChatType\022\014\n\004text\030\003 \001(\t\022\016\n\006fromId\030\004 \001(" +
      "\005\022\014\n\004toId\030\006 \001(\005\022\r\n\005group\030\010 \001(\t\0222\n\014messag" +
      "esType\030\t \001(\0162\034.src.main.proto.MessagesTy" +
      "pe\"\"\n\022BeginToLiveReqBody\022\014\n\004time\030\001 \001(\003\"`",
      "\n\023BeginToLiveRespBody\022\014\n\004time\030\001 \001(\003\022\016\n\006l" +
      "iveid\030\002 \001(\003\022\026\n\016rtmppublishurl\030\003 \001(\t\022\023\n\013r" +
      "tmpliveurl\030\004 \001(\t\"\036\n\016EndLiveReqBody\022\014\n\004ti" +
      "me\030\001 \001(\003\"/\n\017EndLiveRespBody\022\014\n\004time\030\001 \001(" +
      "\003\022\016\n\006liveid\030\002 \001(\003*f\n\nDeviceType\022\026\n\022DEVIC" +
      "E_TYPE_UNKNOW\020\000\022\022\n\016DEVICE_TYPE_PC\020\001\022\027\n\023D" +
      "EVICE_TYPE_ANDROID\020\002\022\023\n\017DEVICE_TYPE_IOS\020" +
      "\003*\262\003\n\007Command\022\022\n\016COMMAND_UNKNOW\020\000\022\031\n\025COM" +
      "MAND_HANDSHAKE_REQ\020\001\022\032\n\026COMMAND_HANDSHAK" +
      "E_RESP\020\002\022\024\n\020COMMAND_AUTH_REQ\020\003\022\025\n\021COMMAN",
      "D_AUTH_RESP\020\004\022\032\n\026COMMAND_JOIN_GROUP_REQ\020" +
      "\005\022\033\n\027COMMAND_JOIN_GROUP_RESP\020\006\022\"\n\036COMMAN" +
      "D_JOIN_GROUP_NOTIFY_RESP\020\007\022\024\n\020COMMAND_CH" +
      "AT_REQ\020\010\022\025\n\021COMMAND_CHAT_RESP\020\t\022\032\n\026COMMA" +
      "ND_START_SHOW_REQ\020\n\022\033\n\027COMMAND_START_SHO" +
      "W_RESP\020\013\022\030\n\024COMMAND_END_SHOW_REQ\020\014\022 \n\034CO" +
      "MMAND_END_SHOW_NOTIFY_RESP\020\r\022\031\n\025COMMAND_" +
      "HEARTBEAT_REQ\020\016\022\025\n\021COMMAND_CLOSE_REQ\020\017*\320" +
      "\001\n\017JoinGroupResult\022\034\n\030JOIN_GROUP_RESULT_" +
      "UNKNOW\020\000\022\030\n\024JOIN_GROUP_RESULT_OK\020\001\022\037\n\033JO",
      "IN_GROUP_RESULT_NOT_EXIST\020\002\022 \n\034JOIN_GROU" +
      "P_RESULT_GROUP_FULL\020\003\022!\n\035JOIN_GROUP_RESU" +
      "LT_IN_BACKLIST\020\004\022\037\n\033JOIN_GROUP_RESULT_TA" +
      "KEOUTED\020\005*M\n\010ChatType\022\024\n\020CHAT_TYPE_UNKNO" +
      "W\020\000\022\024\n\020CHAT_TYPE_PUBLIC\020\001\022\025\n\021CHAT_TYPE_P" +
      "RIVATE\020\002*R\n\014MessagesType\022\010\n\004TEXT\020\000\022\r\n\tLI" +
      "NK_TEXT\020\001\022\016\n\nLINK_IMGAE\020\002\022\014\n\010LINK_PAY\020\003\022" +
      "\013\n\007RED_PAY\020\004B\033\n\027com.zhongweixian.entityP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_src_main_proto_AuthReqBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_src_main_proto_AuthReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_AuthReqBody_descriptor,
        new java.lang.String[] { "Time", "DeviceId", "Token", "DeviceType", "Cid", "AppVersion", "DeviceInfo", "Seq", "Sign", });
    internal_static_src_main_proto_AuthRespBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_src_main_proto_AuthRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_AuthRespBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_src_main_proto_JoinReqBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_src_main_proto_JoinReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_JoinReqBody_descriptor,
        new java.lang.String[] { "Time", "Group", });
    internal_static_src_main_proto_JoinRespBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_src_main_proto_JoinRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_JoinRespBody_descriptor,
        new java.lang.String[] { "Time", "Result", "Group", });
    internal_static_src_main_proto_MessagesReqBody_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_src_main_proto_MessagesReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_MessagesReqBody_descriptor,
        new java.lang.String[] { "Time", "ChatType", "Text", "Group", "FromId", "ToId", "MessagesType", });
    internal_static_src_main_proto_MessagesRespBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_src_main_proto_MessagesRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_MessagesRespBody_descriptor,
        new java.lang.String[] { "Time", "Type", "Text", "FromId", "ToId", "Group", "MessagesType", });
    internal_static_src_main_proto_BeginToLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_src_main_proto_BeginToLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_BeginToLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_src_main_proto_BeginToLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_src_main_proto_BeginToLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_BeginToLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "Liveid", "Rtmppublishurl", "Rtmpliveurl", });
    internal_static_src_main_proto_EndLiveReqBody_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_src_main_proto_EndLiveReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_EndLiveReqBody_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_src_main_proto_EndLiveRespBody_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_src_main_proto_EndLiveRespBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_src_main_proto_EndLiveRespBody_descriptor,
        new java.lang.String[] { "Time", "Liveid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
