// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface EndLiveRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.EndLiveRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *本次直播id
   * </pre>
   *
   * <code>optional int64 liveid = 2;</code>
   */
  long getLiveid();
}
