// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface JoinReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.JoinReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>optional string group = 2;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>optional string group = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
