// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface JoinRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.JoinRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>optional .src.main.proto.JoinGroupResult result = 2;</code>
   */
  int getResultValue();
  /**
   * <code>optional .src.main.proto.JoinGroupResult result = 2;</code>
   */
  com.zhongweixian.entity.JoinGroupResult getResult();

  /**
   * <code>optional string group = 3;</code>
   */
  java.lang.String getGroup();
  /**
   * <code>optional string group = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
