// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface MessagesReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.MessagesReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType chatType = 2;</code>
   */
  int getChatTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType chatType = 2;</code>
   */
  com.zhongweixian.entity.ChatType getChatType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   *发送者ID，
   * </pre>
   *
   * <code>optional int32 fromId = 5;</code>
   */
  int getFromId();

  /**
   * <pre>
   *接受者ID
   * </pre>
   *
   * <code>optional int32 toId = 6;</code>
   */
  int getToId();

  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 7;</code>
   */
  int getMessagesTypeValue();
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 7;</code>
   */
  com.zhongweixian.entity.MessagesType getMessagesType();
}
