// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

/**
 * <pre>
 **
 * 聊天响应
 * </pre>
 *
 * Protobuf type {@code src.main.proto.MessagesRespBody}
 */
public  final class MessagesRespBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:src.main.proto.MessagesRespBody)
    MessagesRespBodyOrBuilder {
  // Use MessagesRespBody.newBuilder() to construct.
  private MessagesRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessagesRespBody() {
    time_ = 0L;
    type_ = 0;
    text_ = "";
    fromId_ = 0;
    toId_ = 0;
    group_ = "";
    messagesType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MessagesRespBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 32: {

            fromId_ = input.readInt32();
            break;
          }
          case 48: {

            toId_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            group_ = s;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            messagesType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhongweixian.entity.Chat.internal_static_src_main_proto_MessagesRespBody_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhongweixian.entity.Chat.internal_static_src_main_proto_MessagesRespBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhongweixian.entity.MessagesRespBody.class, com.zhongweixian.entity.MessagesRespBody.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType type = 2;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType type = 2;</code>
   */
  public com.zhongweixian.entity.ChatType getType() {
    com.zhongweixian.entity.ChatType result = com.zhongweixian.entity.ChatType.valueOf(type_);
    return result == null ? com.zhongweixian.entity.ChatType.UNRECOGNIZED : result;
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  private volatile java.lang.Object text_;
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMID_FIELD_NUMBER = 4;
  private int fromId_;
  /**
   * <pre>
   *发送聊天消息的用户id
   * </pre>
   *
   * <code>optional int32 fromId = 4;</code>
   */
  public int getFromId() {
    return fromId_;
  }

  public static final int TOID_FIELD_NUMBER = 6;
  private int toId_;
  /**
   * <pre>
   *目标用户id
   * </pre>
   *
   * <code>optional int32 toId = 6;</code>
   */
  public int getToId() {
    return toId_;
  }

  public static final int GROUP_FIELD_NUMBER = 8;
  private volatile java.lang.Object group_;
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 8;</code>
   */
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 8;</code>
   */
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGESTYPE_FIELD_NUMBER = 9;
  private int messagesType_;
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
   */
  public int getMessagesTypeValue() {
    return messagesType_;
  }
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
   */
  public com.zhongweixian.entity.MessagesType getMessagesType() {
    com.zhongweixian.entity.MessagesType result = com.zhongweixian.entity.MessagesType.valueOf(messagesType_);
    return result == null ? com.zhongweixian.entity.MessagesType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (type_ != com.zhongweixian.entity.ChatType.CHAT_TYPE_UNKNOW.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
    }
    if (fromId_ != 0) {
      output.writeInt32(4, fromId_);
    }
    if (toId_ != 0) {
      output.writeInt32(6, toId_);
    }
    if (!getGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, group_);
    }
    if (messagesType_ != com.zhongweixian.entity.MessagesType.TEXT.getNumber()) {
      output.writeEnum(9, messagesType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (type_ != com.zhongweixian.entity.ChatType.CHAT_TYPE_UNKNOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
    }
    if (fromId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, fromId_);
    }
    if (toId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, toId_);
    }
    if (!getGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, group_);
    }
    if (messagesType_ != com.zhongweixian.entity.MessagesType.TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, messagesType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhongweixian.entity.MessagesRespBody)) {
      return super.equals(obj);
    }
    com.zhongweixian.entity.MessagesRespBody other = (com.zhongweixian.entity.MessagesRespBody) obj;

    boolean result = true;
    result = result && (getTime()
        == other.getTime());
    result = result && type_ == other.type_;
    result = result && getText()
        .equals(other.getText());
    result = result && (getFromId()
        == other.getFromId());
    result = result && (getToId()
        == other.getToId());
    result = result && getGroup()
        .equals(other.getGroup());
    result = result && messagesType_ == other.messagesType_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + FROMID_FIELD_NUMBER;
    hash = (53 * hash) + getFromId();
    hash = (37 * hash) + TOID_FIELD_NUMBER;
    hash = (53 * hash) + getToId();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (37 * hash) + MESSAGESTYPE_FIELD_NUMBER;
    hash = (53 * hash) + messagesType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhongweixian.entity.MessagesRespBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhongweixian.entity.MessagesRespBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 聊天响应
   * </pre>
   *
   * Protobuf type {@code src.main.proto.MessagesRespBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:src.main.proto.MessagesRespBody)
      com.zhongweixian.entity.MessagesRespBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhongweixian.entity.Chat.internal_static_src_main_proto_MessagesRespBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhongweixian.entity.Chat.internal_static_src_main_proto_MessagesRespBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhongweixian.entity.MessagesRespBody.class, com.zhongweixian.entity.MessagesRespBody.Builder.class);
    }

    // Construct using com.zhongweixian.entity.MessagesRespBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      time_ = 0L;

      type_ = 0;

      text_ = "";

      fromId_ = 0;

      toId_ = 0;

      group_ = "";

      messagesType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhongweixian.entity.Chat.internal_static_src_main_proto_MessagesRespBody_descriptor;
    }

    public com.zhongweixian.entity.MessagesRespBody getDefaultInstanceForType() {
      return com.zhongweixian.entity.MessagesRespBody.getDefaultInstance();
    }

    public com.zhongweixian.entity.MessagesRespBody build() {
      com.zhongweixian.entity.MessagesRespBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.zhongweixian.entity.MessagesRespBody buildPartial() {
      com.zhongweixian.entity.MessagesRespBody result = new com.zhongweixian.entity.MessagesRespBody(this);
      result.time_ = time_;
      result.type_ = type_;
      result.text_ = text_;
      result.fromId_ = fromId_;
      result.toId_ = toId_;
      result.group_ = group_;
      result.messagesType_ = messagesType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhongweixian.entity.MessagesRespBody) {
        return mergeFrom((com.zhongweixian.entity.MessagesRespBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhongweixian.entity.MessagesRespBody other) {
      if (other == com.zhongweixian.entity.MessagesRespBody.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.getFromId() != 0) {
        setFromId(other.getFromId());
      }
      if (other.getToId() != 0) {
        setToId(other.getToId());
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        onChanged();
      }
      if (other.messagesType_ != 0) {
        setMessagesTypeValue(other.getMessagesTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhongweixian.entity.MessagesRespBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhongweixian.entity.MessagesRespBody) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>optional int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>optional int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>optional int64 time = 1;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>optional .src.main.proto.ChatType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>optional .src.main.proto.ChatType type = 2;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>optional .src.main.proto.ChatType type = 2;</code>
     */
    public com.zhongweixian.entity.ChatType getType() {
      com.zhongweixian.entity.ChatType result = com.zhongweixian.entity.ChatType.valueOf(type_);
      return result == null ? com.zhongweixian.entity.ChatType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>optional .src.main.proto.ChatType type = 2;</code>
     */
    public Builder setType(com.zhongweixian.entity.ChatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天类型
     * </pre>
     *
     * <code>optional .src.main.proto.ChatType type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>optional string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>optional string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>optional string text = 3;</code>
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>optional string text = 3;</code>
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *聊天内容
     * </pre>
     *
     * <code>optional string text = 3;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private int fromId_ ;
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>optional int32 fromId = 4;</code>
     */
    public int getFromId() {
      return fromId_;
    }
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>optional int32 fromId = 4;</code>
     */
    public Builder setFromId(int value) {
      
      fromId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送聊天消息的用户id
     * </pre>
     *
     * <code>optional int32 fromId = 4;</code>
     */
    public Builder clearFromId() {
      
      fromId_ = 0;
      onChanged();
      return this;
    }

    private int toId_ ;
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>optional int32 toId = 6;</code>
     */
    public int getToId() {
      return toId_;
    }
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>optional int32 toId = 6;</code>
     */
    public Builder setToId(int value) {
      
      toId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标用户id
     * </pre>
     *
     * <code>optional int32 toId = 6;</code>
     */
    public Builder clearToId() {
      
      toId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object group_ = "";
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>optional string group = 8;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>optional string group = 8;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>optional string group = 8;</code>
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>optional string group = 8;</code>
     */
    public Builder clearGroup() {
      
      group_ = getDefaultInstance().getGroup();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目标组id
     * </pre>
     *
     * <code>optional string group = 8;</code>
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      group_ = value;
      onChanged();
      return this;
    }

    private int messagesType_ = 0;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
     */
    public int getMessagesTypeValue() {
      return messagesType_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
     */
    public Builder setMessagesTypeValue(int value) {
      messagesType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
     */
    public com.zhongweixian.entity.MessagesType getMessagesType() {
      com.zhongweixian.entity.MessagesType result = com.zhongweixian.entity.MessagesType.valueOf(messagesType_);
      return result == null ? com.zhongweixian.entity.MessagesType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
     */
    public Builder setMessagesType(com.zhongweixian.entity.MessagesType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messagesType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
     */
    public Builder clearMessagesType() {
      
      messagesType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:src.main.proto.MessagesRespBody)
  }

  // @@protoc_insertion_point(class_scope:src.main.proto.MessagesRespBody)
  private static final com.zhongweixian.entity.MessagesRespBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhongweixian.entity.MessagesRespBody();
  }

  public static com.zhongweixian.entity.MessagesRespBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessagesRespBody>
      PARSER = new com.google.protobuf.AbstractParser<MessagesRespBody>() {
    public MessagesRespBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessagesRespBody(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessagesRespBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessagesRespBody> getParserForType() {
    return PARSER;
  }

  public com.zhongweixian.entity.MessagesRespBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

