// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.zhongweixian.entity;

public interface MessagesRespBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:src.main.proto.MessagesRespBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>optional .src.main.proto.ChatType type = 2;</code>
   */
  com.zhongweixian.entity.ChatType getType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>optional string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *发送聊天消息的用户id
   * </pre>
   *
   * <code>optional int32 fromId = 4;</code>
   */
  int getFromId();

  /**
   * <pre>
   *目标用户id
   * </pre>
   *
   * <code>optional int32 toId = 6;</code>
   */
  int getToId();

  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 8;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *目标组id
   * </pre>
   *
   * <code>optional string group = 8;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
   */
  int getMessagesTypeValue();
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>optional .src.main.proto.MessagesType messagesType = 9;</code>
   */
  com.zhongweixian.entity.MessagesType getMessagesType();
}
